### ISSUE TITLE
TPS App Docs

### ISSUE THREAD

**Issue by yeqbfgxjiq** [aragoncoop/coop-dao-docs#1]
Currently the docs explain the general thinking behind the Coop DAO, but don't explain HOW we make it happen. HOW we make it happen is via Aragon and it's apps. It would be great to highlight each of the TSP apps or general Aragon apps used in the Coop DAO, explain how they work, and link to the official product page.

Auturk Resources
- app explanations: https://www.autark.xyz/aragon-apps
- repo: https://github.com/AutarkLabs/planning-suite
- app demos: https://tps.autark.xyz

@stellarmagnet I want to be as effecient as possible allocating resources/time to getting things done and making forward progress rather than duplicating things (esp since I'm doing all this just for fun as a volunteer). Do you guys have docs/tutorials for TPS apps and/or do you plan on building them or know anyone who is? [For reference I also asked this same question to the hack.aragon team](https://github.com/aragon/hack/issues/141)

**Comment by stellarmagnet** [comment]
We definitely are interested in more documentation around our apps, if others want to help with it that would be great too. I personally won't have time until about 1-2 weeks from now, so it matters what the urgency is.

I need to update our website still...

This has better app descriptions: https://medium.com/@stellarmagnet/that-planning-suite-live-on-rinkeby-c2332e2e5e27

I just saw this tutorial, and i think the format is pretty cool: https://medium.com/mybit-dapp/mybit-dao-tutorial-5b3bc093963b

Here is a guide for installing our apps:
https://github.com/AutarkLabs/planning-suite/blob/master/docs/GETTING_STARTED.md
Here are some of our app screenshots (missing rewards): https://www.dropbox.com/s/tw478e6lsumvumr/App%20screenshots.zip?dl=0

Note: instead of `tps.autark.xyz` i'd reference `rinkeby.autark.xyz`

In general, resources that would be nice:
1) One video demo per app (except Dot Voting won't have an independent video; may be better to show it both in the Projects and Allocations video)
2) One combined video that shows all of the apps in action 
3) Detailed written tutorial per app (similar to the MyBit one).

**Comment by yeqbfgxjiq** [comment]
Cool! Thanks for all these resources. I don't have the skills/desire to make videos, but documentation would help with OWL as well as the Coop DAO. If you're busy I'll just explore the TPS apps that are in the Coop DAO, figure out how they work and write that down, and then post updates to this thread so that you can weigh in with feedback :)

**Comment by stellarmagnet** [comment]
Sounds like a good plan @burrrata!

**Comment by yeqbfgxjiq** [comment]
As I mentioned on Keybase, [forked](https://github.com/burrrata/the-coop) this project so that I can brainstorm/build in peace without stepping on anyone's toes. Holding off on merging until the coop decides if they want to move forward with the project or not. I'll post updates on Autark TPS docs for the Coop DAO [here](https://github.com/burrrata/the-coop/issues/7)
